### ISSUE TITLE
Names of the policies should be read from the annotation policies.kyverno.io/title

### ISSUE THREAD

**Issue by eddycharly** [kyverno/playground#117]
Names of the policies should be read from the annotation [policies.kyverno.io/title](http://policies.kyverno.io/title)

**Comment by fjogeleit** [comment]
I can not read them directly from the resource, this would mean I have to load all policies only for displaying the name. But I can rename them in the examples Drawer

**Comment by eddycharly** [comment]
I did not add it to the milestone because it may require some discussion.

I would like to understand what the annotation brings and where this should be used.

**Comment by fjogeleit** [comment]
Currently the examples are named like the Policy File `disallow-capabilities-strict.yaml` => `disallow capabilities strict`. The annotation contains a more readable / formatted name like `Disallow Capabilities Strict`.

SO I think the goal is just to have a more readable / formatted Title for the examples.

**Comment by eddycharly** [comment]
Is this in the menu on the left ?

**Comment by fjogeleit** [comment]
Yes, correctly
