### ISSUE TITLE
Clarify Download Policy button

### ISSUE THREAD

**Issue by eddycharly** [kyverno/playground#121]
I don't understand the Download Policy button that's accessible after the results are shown. It suggests that the policy is somehow materially different from its contents on the main page but it of course isn't. What may make more sense in place of just downloading the policy here is to download the test results along with the policy, resource, and context (including vars).

**Comment by fjogeleit** [comment]
The intention was only to able able to download an policy when its working as expected. I am don't think that downloading everything in a single file is very helpful. We can also just drop this button
