### ISSUE TITLE
Add more template resources

### ISSUE THREAD

**Issue by eddycharly** [kyverno/playground#127]
There needs to be more Template resources available. Pod, Deployment, StatefulSet, DaemonSet, Job, CronJob, Secret, ConfigMap, Ingress, Service, Namespace, PersistentVolume, ReplicaSet, ResourceQuota, ServiceAccount, NetworkPolicy, ClusterRoleBinding, ClusterRole, RoleBinding, Role, PriorityClass.

**Comment by eddycharly** [comment]
@chipzoller can you add the templates in https://github.com/kyverno/playground/tree/main/frontend/public/templates ?

**Comment by chipzoller** [comment]
Will do

**Comment by fjogeleit** [comment]
to get them into the select you need to add them here:

https://github.com/kyverno/playground/blob/main/frontend/src/components/TemplateButton.vue#L16

maybe I can automate this in the future, currently its a manually task
