### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by chipzoller** [kyverno/playground#201]
Simple button to copy any panel's contents to clipboard would be nice.

**Comment by fjogeleit** [comment]
Hm ne toolbar already has some buttons and space is running out, do you think its necessary? Because all inputs are in an editor its quite easy to copy it via CMD + A / CMD + V

**Comment by chipzoller** [comment]
It's not a big deal but multiple keyboard shortcuts just add more steps. Copy buttons are common in cases like these because they improve UX.

**Comment by fjogeleit** [comment]
hm but we still have space limitations, especially in the resources panel. To solve this we could consider to remove the test from the icons and using tooltips instead.

**Comment by fjogeleit** [comment]
@chipzoller current layout: removed labels from import buttons and added tooltips, more space for additional buttons like copy button. UX should be okay, wdyt?

<img width="1678" alt="Bildschirmfoto 2023-05-22 um 09 49 28" src="https://github.com/kyverno/playground/assets/16627596/c2f89e02-189d-4116-85b6-6038006af221">
<img width="1680" alt="Bildschirmfoto 2023-05-22 um 09 49 44" src="https://github.com/kyverno/playground/assets/16627596/132ea8a8-15b6-4efc-902d-0b9d3900bdd8">

**Comment by chipzoller** [comment]
Perfect, Frank, this is exactly what I had in mind. Tooltips for EVERYTHING is one of the easiest ways to improve UX at basically no UI real estate cost.

**Comment by fjogeleit** [comment]
okay, then I close this issue
