### ISSUE TITLE
Define our image tagging strategy

### ISSUE THREAD

**Issue by eddycharly** [kyverno/playground#251]
What `latest` means ?
How do tag dev images ?

Proposal:
- dev images are tagged with commit hash
- `latest` is only for stable images

**Comment by fjogeleit** [comment]
Sounds good to me

**Comment by eddycharly** [comment]
I don't think we should tag `latest` dev images, to me it should only apply to stable images.

**Comment by eddycharly** [comment]
Ok, i need to check how to tell goreleaser to not tag latest when doing a prerelease.

**Comment by eddycharly** [comment]
Started discussion [here](https://github.com/orgs/goreleaser/discussions/4042)
