### ISSUE TITLE
Template resource misspellings

### ISSUE THREAD

**Issue by chipzoller** [kyverno/playground#258]
PersistentVolume
PersistentVolumeClaim

**Comment by chipzoller** [comment]
The category needs to be "Templates" (plural, not singular 'Template')

**Comment by chipzoller** [comment]
Can the Templates icon have a tool tip?

**Comment by fjogeleit** [comment]
is it fine this way?

<img width="406" alt="Bildschirmfoto 2023-05-24 um 10 27 15" src="https://github.com/kyverno/playground/assets/16627596/9d4c376a-1271-4acb-a4c2-081d1603c2cd">
