### ISSUE TITLE
Onboarding Improvements

### ISSUE THREAD

**Issue by fjogeleit** [kyverno/playground#316]
With #314

now onboarding steps were added, we also have new advanced panels with info text.

This text could be extended and improved.

Onboarding:

https://github.com/kyverno/playground/blob/main/frontend/src/composables/onboarding.ts

Info Text:

https://github.com/kyverno/playground/blob/main/frontend/src/config.ts#L40-L43

**Comment by eddycharly** [comment]
@fjogeleit is this for `v0.3.0` ?

**Comment by fjogeleit** [comment]
Yes relates to #290
