### ISSUE TITLE
autosuggestion/tab-complete is over-eager

### ISSUE THREAD

**Issue by zswanson** [kyverno/playground#348]
The auto-suggest/tab-complete feature triggers almost instantly on a new line and gets in the way. It needs a more of a delay before popping up. Right now if I enter a new line while typing in a policy and continue typing immediately there is a good chance that if you are trying to tab-in to add a sub element such as a list or dict entry will immediately fill in the suggestion.

**Comment by eddycharly** [comment]
@fjogeleit was this fixed ?

**Comment by fjogeleit** [comment]
I improved it as much as I can right now. Will see after the release if it solves the issue completely

**Comment by fjogeleit** [comment]
@zswanson can you check if the new behavior is better and fixes your issue?

**Comment by fjogeleit** [comment]
I will close this issue for now, feel free to reopen it if you still have issues with it.

**Comment by zswanson** [comment]
Sorry didn't see this update! Yes, much improved!
