### ISSUE TITLE
mutating policy result showing mutation on the wrong resource

### ISSUE THREAD

**Issue by sgandon** [kyverno/playground#689]
in [this playground](https://playground.kyverno.io/next/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFfjjBQICZSQkBaPNFOjrpKwRxw8Kq3AAWaEgHMcbgIwVy0SHUUHDRwAUQAPGEk%2BPwB5EllYRABVMHUpCgAzNCgXbXI8USgcAjCdK119HApbKHtrIxMzHAtHEmdXd2tRXOiyiI1vWp1p3wQp6fJ69wIIUTw4avmF6d4BGrHtuvIAZQGVA8O9ZWC0Df3ww%2Bn6zhAAKheDsHc4Un4YCWIJHuh2KUC2R0oODm5BewGA7gAjqJqhJGBAQngNIDyAAfHHkADkACEAIJCADSAHEAEopLIAOQAIgSAL4sj4PQ7o/AaCB4CgxJHFAgXaY0YrIihZaSMkkAFRiB0iqnyotUeACEmBj3qGGw%2BCIpAoGDABDYXE5j12gnIjOMpnMOEsooWV2qYFuTRhIDh5RwSJRaIARgArVyo5SqPJoRhum4bchsjmPaZfVy/f6AmrkADEBT4f385A6Dp65AkPgk5HEOHLXlrwzyOH45BcbhU5DQBHITpoVnFhBd21m4MeOcWVChFFhwHVmsYwVcjCkihM0QXITgjAA2nx/kJSKo%2BAaADTkH6WNDHwgAXW3N8YvYAYrZFPeF2cJNScAVY40kyAuYMFWUiSM2Q4LOOOjcpiEh8hQJIkAgACSJAQdMUHkOKYheuhOiYc8PrAH6AaSMGYZwBGKhqBoMZuom7KASmeETpC0IznOKgbkuK5rlI3FbruJD7oeV4kKe56ideBB3g%2BvbvthyIvhAigfu2EjklC36/m6AEsdBGK8vy5CIShaGWimOiKbhFmWYRvqIsiZEQKG4aMJGNGqH%2BygMS8lmih6EjeMcEiwTgfjwAAsvgAQUDmjbRHWta%2BMBWKkOWEDlngMB%2BAEeB%2BpIaB4BIQ6LnAo4LLxUDRBV2wedGtUgiQqUAqQ2qWdsCKwJQjA/IoLChTleXLOqEjTkRmICCpAAUBLbgADFYACcaBWAAXjewAAKwsgSACUekkCAJ4gMsqzrDgKDoJguCEICFAcNw1oUKc6lKNRDVlG6FCKAg/RvQ8cYehshg/mglQlZYCAhBQKQegG3CfQ8NZ4AA%2Bh6BAEAA7nyNoAFqKEtNBCH4AC8pO5kGAAaUBYwAmlT9JrfwABMS0IHjJLk7mBNEyT3PcNwVjC9weq3YaZCdmAprmk9BYUHanSOs6JD1bRUzfboEUkHEVglmYPRlNVQY4CUWwmhQ/h8HEQSblM7gmPAXYUAAzGULhVJR8FKhMXgADJoCbZuihbWvW2UVU1UqH3q6Kxum%2B1w7S5b2s25aZWjheR7iYQo71JrVs60OMCKGgsVhzryDsIw7AACw10OkDFYnCz1FnYkyHyY3kAAHPNQ69o1E6a1kxwxNSqPSCSxzHAA6ik1KMix1nKYoQ8LG2gyaQg2nr9smu/f9gz6TsU7Vi4aMY9juPcMdIDQPw34rGsGxXWLBr3VhFrPScn7vVGsdAaNB%2Bn9Te5wgHXGBl6IwRQIbcAkNDL0cM0AIwEIAnQKN0ZdmvngG01NaYMyZqzdmnNuY5nwfTRmzM2Ycy5hTHMvNiZkwpoLPoIs9A3Q/kaKWMtHo8Hlrae0BsnSQzVpoL6wCK6631srSGOh47B0tKHQuacM5lAdpkZ25A3YPA9uGb2lpS5BX9oHBOo5lGpwjt0PiTRo4APEbZBRLcZjJykQcNRtl27STzg0AwbjbI6BLmXL0Kiq413rhaFMTctS1TblJHOshioUD7gPEgNAh750kaPcek9p5zwXkvAJ2wV6vj3joMBGktI/jKdMA%2BoC/5FJTGxCgmCr441wbfE6WccBxAkFdSgogTZ4HEqBKYdA7rcIJNXFmPcCSsO6b0qYKNNYEjmQ8PwthhjZnvOo6AmxyA7IeHAMQYE8DUj2dsm8EjIGegDkHbMwB2QPBgmlSW0pZQKjKPwPAO9RCSyKCUQI5kCjVT8NqH4RA/BkAOEEgIxwcp6AkGsHA35IBEDgj8igqyyg9I2GAVqQIthOkDlUG0oVkQHCBp6LFaydAFD5BsJ8V4xDuAyPIZCUK%2BS2MtMSoMpLCjCiBToL4EApCUUir4YJj9qjnTuESvQfLmwCsBTihVVQ7QFHwO4fgfsIBqGSPKklSryAAtKOsp0PIpBYGKDAPIyQST8EUIkCWbLECGsVTaU1Qq/QRUkJig4oIIBY1Qm2ZFyqzULDAJUKAr1BiXIOO2IwlgYDFAABKmwxM4%2BoMDwZQDkdsXUpc1qkFFLqNayLS3kAihWQZla/AQAgH4KorCBwpsVQ8lkd8Lz5j8G/ThEzJZ8J/geEgPaJVgH/p5NAGtJHUHGQwa57pqVUFoPQCAiN0E9jVTgDVuavzhUSKFBAkUogEqxeSnAtLixgwht%2BX1R7DAQDgJCPAzB10PHHH1UurZjBFWiC2WAkgcVxGOaIIwlJNmmixQQBAYE14MCMAQK9n6VLfpcB6MKAHD3AdA0YLIF84w0rKChxQaHf2YfIIB/NuKxBGHOVUbM2KP2SVI2gH9GH/2Ueww8GjYGcAiHEFIM5FyiMPDOi/HAT4YB5oNBQHEBxtyvBPHOtdJ5XhXMtNuGIdBLBqbUxphYinlODJwM4WDK59MKaUwMk2Vgo18vgJZzT1mTNWAQ6ZqoXYcBOcM/SCARg9PqYUySaQyFTh4BoPAbzSmguablBASEJBvyRZwFjQLBnpjbmOIMiiEgSRwDuAQZLMBUvpYU6cKABRsuuUovlwrxXSsxYyzobcRICzJDK5p1FmjTgSE64Zh1TrMaAlRV3frmWBOnMG86kbxgxtNYU0SW4lANmrAEMcOAvhRvFXGy1ybQmlvPtW38/gG2ttzZ2wtzT%2B38D0ei8p1dwyIDIFi4Zm7wmqhtYEB16zj2GAveawc8LkWNh1bW31lTT2HvzogID7cI6x0YGh6pyHDA4cI5yuO5HUPUcQCsJGbKcAZIKcVqWER2OGAU9hwpgAUi5KnVOrBeAbZQOz7g9amxUDgOH9IVDtMoK6hADPcdw9kPwRkiQKj4sBESMDmphd/ep11vZCuYcA4U3dr7hY/Cq7XerzTsaVC66e84GgW5ccLjN4wV7mXgdReNwwU3cA4d242A7vHBAzf45UIT4nBv8Ag5wJFUg/w%2BTu6d/0CLUX8ch4xaL/z4fQISBvF2wTKkn6yp3T%2BPcBKCBXS7ScoTGeJN59QHfXFxhc/55ZEAA) you can find a policy watching secret changes and mutating the deployment that uses this secret on changes.

On the playground, whether you add the deployment resource in the cluster resources or in the main resource screen. When you click on start and from the showing dialog you click on details, the resulting changes resource ends up being the Secret and not the Deployment as expected.

**Comment by fjogeleit** [comment]
thanks for your report, sorry for the late response, I prepared a fix for it.

Please be aware of that target resources needs to be added as cluster resources. In the resource editor are only resources which should run directly against your policy. You also need to set an explicit namespace in your deployment because we don't set any defaults.

**Comment by fjogeleit** [comment]
Fix is released with v0.4.1 and available over the public Playground: [test policy](https://playground.kyverno.io/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFfjjBQICZSQkBaPNFOjrpKwRxw8Kq3AAWaEgHMcbgIwVy0SHUUHDRwAUQAPGEk%2BPwB5EllYRABVMHUpCgAzNCgXbXI8USgcAjCdK119HApbKHtrIxMzHAtHEmdXd2tRXOiyiI1vWp1p3wQp6fJ69wIIUTw4avmF6d4BGrHtuvIAZQGVA8O9ZWC0Df3ww%2Bn6zhAAKheDsHc4Un4YCWIJHuh2KUC2R0oODm5BewGA7gAjqJqhJGBAQngNIDyAAfHHkADkACEAIJCADSAHEAEopLIAOQAIgSAL4sj4PQ7o/AaCB4CgxJHFAgXaY0YrIihZaSMkkAFRiB0iqnyotUeACEmBj3qGGw%2BCIpAoGDABDYXE5j12gnIjOMpnMOEsooWV2qYFuTRhIDh5RwSJRaIARgArVyo5SqPJoRhum4bchsjmPaZfVy/f6AmrkADEBT4f385A6Dp65AkPgk5HEOHLXlrwzyOH45BcbhU5DQBHITpoVnFhBd21m4MeOcWVChFFhwHVmsYwVcjCkihM0QXITgjAA2nx/kJSKo%2BAaADTkH6WNDHwgAXW3N8YvYAYrZFPeF2cJNScAVY40kyAuYMFWUiSM2Q4LOOOjcpiEh8hQJIkAgACSJAQdMUHkOKYheuhOiYc8PrAH6AaSMGYZwBGKhqBoMZuom7KASmeETpC0IznOKgbkuK5rlI3FbruJD7oeV4kKe56ideBB3g%2BvbvthyIvhAigfu2EjklC36/m6AEsdBGK8vy5CIShaGWimOiKbhFmWYRvqIsiZEQKG4aMJGNGqH%2BygMS8lmih6EjeMcEiwTgfjwAAsvgAQUDmjbRHWta%2BMBWKkOWEDlngMB%2BAEeB%2BpIaB4BIQ6LnAo4LLxUDRBV2wedGtUgiQqUAqQ2qWdsCKwJQjA/IoLChTleXLOqEjTkRmICCpAAUBLbgADFYACcaBWAAXjewAAKwsgSACUekkCAJ4gMsqzrDgKDoJguCEICFAcNw1oUKc6lKNRDVlG6FCKAg/RvQ8cYehshg/mglQlZYCAhBQKQegG3CfQ8NZ4AA%2Bh6BAEAA7nyNoAFqKEtNBCH4AC8pO5kGAAaUBYwAmlT9JrfwABMS0IHjJLk7mBNEyT3PcMdIDQPw34rGsGxXXqt2GmQWEWs9Jyfu9Ua0VM33kL9/2DF9jTxl6RhFBD3ASNDXpw2gCMCGrZQo%2BjXbY7jFDU7TDNM6z7Oc9zOYu/TjPM2zHNcxTOa88TZMU4LJ0XlIcQSFdlCiEG9AqJsZR0HdRqEuwjAswAHAS3DcDHOBx1MKMawShcPH4tjDNm95lC0mzkI3DxwGIYF4NS0At23OhA56AAyaDJyUFDAOyDwwWlcvSrKCplPweAINSohy0UJSBOZBTVX42o/EQfhkAcMCKGgATHDlegSGsODfpARBwSvFBV2UpcbGArVAlsTqj1UNpQrIgOIPEGhJq46AKHyDYT4rxiHcBkeQyFj58iaAcP%2BQYAGFGFNvHQXwIBSEopFXwF9mxi3OncX%2BehMHNmwVvd%2B1Cqh2gKPgdw/Ah4QDUMkKh/9aHkE3qUGuToeRSCwMUGAeRkgkn4IoRIstEGIB4TQm0AjcF%2BgipIF%2BBxQQQCxqhNsd86GCIWGASoUBXqDAbjeA47YjCWBgMUAAEjgKAGJ2pPGLGDY2tldTnzWqQUUuo1p30CeQCKFYk6hL8BACAfgqhFxIAOBxNDsyTyFnAcQcFFDkIljgZhe5v4ECuukzuUhu7VAodUKWN0DT3U7GAU05onoFgoHaTojpnQkHqjbQGjQKD%2BD4HEKwJYzA9F1tcYGBsvFQEhjoaqY93Emn6RFEgcQgibimO4Ew8AuwUAAMxlBcFUSi8ElQTC8CPBZo4lm6BWWsh4VUapKg%2Bj0w48yXHuIWDcgZqyDhlVHDHMSBpRz1A1j8%2B5KYz6kOWYM5AOd2AABZGAWhTJAYqnyPGAuvLIYqFA87zSHL2RqE4NZZGODEakqNpAkmOMcAA6ikakjIWLWWUooYlCw2yDE0qvH8HLtgay1ly84tkOpsQoHbDGjs8D8CjiAD%2BxhCnFJZEAA)
